services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_PATH=/n8n/
      - N8N_EDITOR_BASE_URL=https://192.168.0.254/n8n/
      - WEBHOOK_URL=https://192.168.0.254/n8n/
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - proxy

volumes:
  n8n_data:

networks:
  proxy:
    external: true
